---

- name: replace configuration with intended configuration
  eos_config:
    src: '{{root_dir}}/intended/configs/{{ inventory_hostname }}.cfg'
    replace: config
    save_when: modified
    backup: yes
    backup_options:
      filename: "{{ inventory_hostname }}_running-config.conf"
      dir_path: "{{ root_dir }}/config_backup/"
  when: eosconfig.changed
  tags: [provision]
